Issues/9
05-Project/infra pull request #16
Opened 2024-11-06 14:57 UTC by GYOUNG-ko

2024-11-07 00:53 UTC, narumir requested changes

2024-11-07 00:53 UTC, narumir commented on vpc.tf
> +  port        = 22
로드벨런서에서 HTTP서비스가 아닌 SSH로 로드 벨런싱을 해야하는 이유가 있을까요?
HTTP 서비스를 주로 지원하는 alb에서 SSH는 어떤 목적인지 모르겠습니다.

2024-11-07 00:53 UTC, narumir commented on vpc.tf
> +    cidr_blocks = ["0.0.0.0/0"]
bastion 역시 SSH를 사용하는데 SSH는 Allow List 방식으로 IP를 제한 하는 방식으로 진행하면 좋을거 같습니다.

2024-11-07 00:53 UTC, narumir commented on vpc.tf
> +    cidr_blocks = ["0.0.0.0/0"]
SSH 역시 공격이 제일 많이 들어오는 포트여서 안전하게 사용이 가능했으면 합니다.

2024-11-07 00:53 UTC, narumir commented on vpc.tf
> +    cidr_blocks = ["0.0.0.0/0"]
RDS를 외부에서 접속해야 할 이유가 있을까요? 
Bastion이 있고 외부에서 접속이 필요하다면 Bastion을 통해서 접속 하면 될거 같습니다.

2024-11-07 00:53 UTC, narumir commented on main.tf
> -  backend "s3" {
backend가 없으면 tfstate 파일이 공유되지 않아 tfstate 파일을 가지고 이쓴 사람 아니면 작업이 불가능합니다.

2024-11-07 00:53 UTC, narumir commented on .gitignore
> +variables.tf
이건 왜 github에 올라가지 못하도록 설정이 되었을까요?

2024-11-07 00:53 UTC, narumir commented on vpc.tf
> +    to_port     = 0
NAT에서 모든 포트를 개방해서 사용하는 이유가 있을까요? 
Nat는 외부에서 트래픽이 들어오는 용도가 아닌걸로 알고 있습니다.

2024-11-07 00:53 UTC, narumir commented on vpc.tf
> +    from_port   = 80
WAS 앞에는 ALB가 있어서 ALB에서만 트레픽을 받을 수 있도록 구성하면 좋을거 같습니다.

2024-11-07 03:17 UTC, GYOUNG-ko commented on main.tf
> -  backend "s3" {
시정하겠습니다

2024-11-07 03:17 UTC, GYOUNG-ko commented on vpc.tf
> +    cidr_blocks = ["0.0.0.0/0"]
고치겠습니다

2024-11-07 10:09 UTC, narumir requested changes

2024-11-07 10:09 UTC, narumir commented on vpc.tf
> +    cidr_blocks = [aws_security_group.bastion_sg.id]
현재 bastion에서만 접근이 가능한데요. 그러면 WAS 에서는 어떻게 접근이 가능 할까요?

2024-11-07 10:09 UTC, narumir commented on vpc.tf
> +  subnet_ids = [
왜 private subnet에 3, 4만 있는지 알 수 있을까요?

2024-11-07 10:09 UTC, narumir commented on vpc.tf
> +    cidr_blocks = ["211.34.202.2"] # 용산 SeSAC IP
CIDR 블록은 뒤에 subnet이 있어야 하는데 ip만 있네요.

2024-11-07 10:09 UTC, narumir commented on vpc.tf
> +    cidr_blocks = [aws_default_vpc.project05_VPC.id] # 내부에서만 접근
이건 VPC  id 이고 네트워크 대역대가 아닙니다.

2024-11-07 10:09 UTC, narumir commented on vpc.tf
> +    cidr_blocks = [aws_instance.bastion_ec2.id] # Bastion Host에서만 접근
이건 ec2 id 이지 네트워크 대역대가 아님니다.

2024-11-08 00:41 UTC, GYOUNG-ko commented on vpc.tf
> +    cidr_blocks = [aws_security_group.bastion_sg.id]
aws_security_group.was_sg.id를 추가해서 접근허용하였습니다

2024-11-08 00:43 UTC, GYOUNG-ko commented on vpc.tf
> +  subnet_ids = [
아키텍처 상으로 맞춰 서브넷을 지정하다보니 3, 4번에만 생성되도록 만들었습니다

2024-11-10 08:42 UTC, baikdk approved these changes

2024-11-11 04:32 UTC, narumir approved these changes

2024-11-11 04:32 UTC, merged